package com.light.security.core.authentication.event;

import com.light.security.core.authentication.token.Authentication;
import com.light.security.core.exception.AuthenticationException;

/**
 * @ClassName AuthenticationFailureProxyUntrustedEvent
 * @Description 指示由于不可信代理生成CAS用户票证而导致身份验证失败的应用程序事件。
 * Application event which indicates authentication failure due to the CAS user's ticket
 * being generated by an untrusted proxy.
 * @Author ZhouJian
 * @Date 2019-12-03
 */
public class AuthenticationFailureProxyUntrustedEvent extends AbstractAuthenticationFailureEvent {
    /**
     * Create a new ApplicationEvent.
     *
     * @param authentication the object on which the event initially occurred (never {@code null})
     * @param exception
     */
    public AuthenticationFailureProxyUntrustedEvent(Authentication authentication, AuthenticationException exception) {
        super(authentication, exception);
    }
}
